javascripts:
  application:
    - public/javascripts/jquery.js
    - public/javascripts/rails.js
    - public/javascripts/jquery.autocomplete.min.js
    - public/javascripts/jquery.textarearesizer.js
    - public/javascripts/jquery.progressbar.min.js
    - public/javascripts/jquery.placeholder.js
    - public/javascripts/application.js

stylesheets:
  application:
    - public/stylesheets/application.css
    - public/stylesheets/formtastic.css
    - public/stylesheets/formtastic_changes.css
    - public/stylesheets/jquery.autocomplete.css
