---
 # Your secret key for verifying the integrity of signed cookies. If you change this key,
 # all old signed cookies will become invalid! Make sure the secret is at least 30
 # characters and all random, no regular words or you'll be exposed to dictionary attacks.
 #
 # You can use "rake secret" to generate a new secret token.
 :secret_token: 'secret'
 :devise:
   :secret_key: 'key'
   :pepper: 'pepper'

 # Host used to configure ActionMailer::Base.default_url_options[:host] as described in:
 # http://api.rubyonrails.org/classes/ActionMailer/Base.html#label-Generating+URLs
 :host: localhost:3000
 # This is used as the sender address for e-mails
 sender_address: no-reply@domain.com

 # SMTP settings are needed if you want to test sending e-mails from your development
 # environment. These settings are used to setup ActionMailer::Base.smtp_settings, as
 # described in:
 #
 # http://api.rubyonrails.org/classes/ActionMailer/Base.html#label-Configuration+options
 #
 # Example:
 # :smtp_settings:
 #   :address: smtp.domain.com
 #   :port: 587
 #   :domain: domain.com
 #   :authentication: :login
 #   :user_name: no-reply@domain.com
 #   :password: password
 smtp_settings:
   address: mail.submissoes.agilebrazil.com
   port: 587
   domain: submissoes.agilebrazil.com
   authentication: :login
   user_name: no-reply@submissoes.agilebrazil.com
   password: 'your_password'
   enable_starttls_auto: false

 # You can use Amazon Simple E-mail Service (SES) to send e-mails too. If you decide
 # to use it, please provide your SES access key and secret key as follows:
 #
 # :ses:
 #   :access_key_id: your_aws_access_key_id
 #   :secret_access_key: your_aws_secret_access_key
 #
 # To test in development mode with SES, you will also need to change
 # config/environments/development.rb and add the following:
 #
 # config.action_mailer.delivery_method = :ses
 ses:
   access_key_id: 'YOUR_AWS_KEY'
   secret_access_key: 'YOUR_AWS_SECRET'

 # The application can be configured to track exceptionr/errors with airbrake, by
 # providing your Airbrake access key as follows:
 #
 # :airbrake:
 #   :access_key: xxx111xxx
 airbrake:
   project_id: 'PROJECT_ID'
   project_key: 'PROJECT_KEY'
   environment: 'staging'

 # To track user access using Google Analytics, please provide your details as follows:
 #
 # :google:
 #   :tracker_id: google_analytics_id
 #   :conversion_id: google_ads_conversion_id
 #   :conversion_label: google_ads_conversion_label